app:
  base-url-bot: "http://localhost:8090"
  base-url:
    git-hub-base-url: "https://api.github.com"
    stack-overflow-base-url: "https://api.stackexchange.com/2.3"

  scheduler:
    enable: true
    interval: 15s
    force-check-delay: 15s

spring:
  datasource:
    driver_class_name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper
  application:
    name: scrapper
  liquibase:
    change-log: ../../../../migrations/master.xml
    enabled: false
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
