app:
  telegram-token: 6863584041:AAEa0ZBYr8SKB0_X8ckJvnT7s5qJqjXPLUE
  base-url-scrapper: "http://localhost:8080"
  retry-config:
    retry-type: linear
    attempts: 5
    min-delay: 100
    status-codes:
      - 500
      - 502
      - 503
      - 404
  kafka:
    bootstrap-server: localhost:9092, localhost:9093, localhost:9094
    topic-name: update-messages-topic
    partitions-count: 1
    replication-count: 3

spring:
  application:
    name: K0lokolchikBot

  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
