app:
  telegram-token: 6863584041:AAEa0ZBYr8SKB0_X8ckJvnT7s5qJqjXPLUE
  base-url-scrapper: "https://localhost:8090"

spring:
  application:
    name: K0lokolchikBot

  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
